# Generated by Django 4.1.6 on 2023-02-21 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_name', models.CharField(max_length=254)),
                ('serial_num', models.PositiveIntegerField()),
                ('status_lock', models.CharField(choices=[('Close', 'Denied'), ('Open', 'Successful')], default='Close', max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='Number',
        ),
    ]
