# Generated by Django 4.1.6 on 2023-02-22 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_devicemodel_delete_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='devicemodel',
            name='status_lock',
        ),
        migrations.AddField(
            model_name='devicemodel',
            name='status',
            field=models.TextField(default='Close'),
        ),
        migrations.AlterField(
            model_name='devicemodel',
            name='device_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='devicemodel',
            name='serial_num',
            field=models.PositiveBigIntegerField(),
        ),
    ]
