# Generated by Django 4.1.6 on 2023-02-22 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_devicemodel_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicemodel',
            name='status',
            field=models.CharField(max_length=10),
        ),
    ]
