# Generated by Django 4.1.6 on 2023-02-22 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_devicemodel_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicemodel',
            name='serial_num',
            field=models.CharField(max_length=255),
        ),
    ]
