# Generated by Django 4.1.6 on 2023-02-26 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_devicemodel_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicemodel',
            name='user',
            field=models.CharField(max_length=255),
        ),
    ]
