# Generated by Django 4.1.6 on 2023-02-27 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_alter_devicemodel_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicemodel',
            name='auth_key',
            field=models.CharField(default='0000', max_length=4),
        ),
    ]
