# Generated by Django 4.1.6 on 2023-03-14 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
