# Generated by Django 4.1.6 on 2023-03-14 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0034_alter_profile_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='image',
            new_name='avatar',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='about_me',
            new_name='bio',
        ),
    ]
