# Generated by Django 4.1.6 on 2023-06-05 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0040_alter_keys_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keys',
            name='key',
            field=models.IntegerField(max_length=4),
        ),
    ]
