# Generated by Django 4.1.6 on 2023-06-05 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0041_alter_keys_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='devicemodel',
            name='auth_key',
        ),
    ]
