# Generated by Django 4.1.6 on 2023-06-05 11:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0042_remove_devicemodel_auth_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='keys',
            name='user',
        ),
        migrations.AddField(
            model_name='keys',
            name='device',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.devicemodel'),
        ),
        migrations.AlterField(
            model_name='keys',
            name='key',
            field=models.CharField(max_length=4),
        ),
    ]
