# Generated by Django 4.2.2 on 2023-10-24 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0043_remove_keys_user_keys_device_alter_keys_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keys',
            name='key',
            field=models.IntegerField(max_length=16),
        ),
    ]
