# Generated by Django 4.2.2 on 2023-11-09 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0045_alter_keys_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='keys',
            name='time',
            field=models.DateTimeField(default=None),
        ),
        migrations.AddField(
            model_name='keys',
            name='used',
            field=models.CharField(default='Temporary', max_length=50),
        ),
    ]
