# Generated by Django 4.2.2 on 2023-11-09 11:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0046_keys_time_keys_used'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keys',
            name='time',
            field=models.DateTimeField(default=datetime.time(0, 0), null=True),
        ),
    ]
