# Generated by Django 4.2.2 on 2023-11-11 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0053_alter_keys_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keys',
            name='used',
            field=models.CharField(choices=[('Const', 'Constant'), ('Temp', 'Temporary'), ('One use', 'One use')], default=('Temp', 'Temporary'), max_length=10),
        ),
    ]
