# Generated by Django 4.2.2 on 2023-12-02 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0057_devicemodel_admin_devicemodel_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicemodel',
            name='sync',
            field=models.CharField(default='False', max_length=10),
        ),
    ]
