# Generated by Django 4.2.2 on 2024-01-02 16:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0058_devicemodel_sync'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keys',
            name='time',
            field=models.DateTimeField(default=datetime.datetime),
        ),
    ]
