# Generated by Django 4.2.2 on 2024-01-03 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0060_alter_keys_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='keys',
            name='selection',
            field=models.CharField(choices=[('-', '0'), ('+1h', '1 hour'), ('+1d', '1 day'), ('+1w', '1 week'), ('+2w', '2 month'), ('+1m', '1 month'), ('+2m', '2 month'), ('+5m', '5 month')], default='-', max_length=100),
        ),
    ]
