# Generated by Django 4.2.2 on 2024-01-03 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0061_keys_selection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicemodel',
            name='sync',
            field=models.CharField(default='False', max_length=5),
        ),
    ]
