# Generated by Django 4.2.2 on 2024-01-07 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0064_remove_keys_time_keys_time_end_keys_time_start'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keys',
            name='time_start',
            field=models.DateTimeField(null=True),
        ),
    ]
